version: "3"
services:
  db:
    # build: ./IMG_MS_SQL
    # image: twx9_db
    image: twx94_db
    ports:
      - "1433:1433"
  twx:
    # build: ./IMG_TWX_9_SQL
    # image: twx9_twx
    image: twx94_app
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./.ThingworxStorage:/ThingworxStorage
