/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twx.core;

import java.util.Scanner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import twx.core.concurrency.imp.AbstractActor;
import twx.core.concurrency.imp.ActorManager;
import twx.core.concurrency.imp.Message;

public class App {

    class Actor extends AbstractActor {
		private final String dest;
		public Actor(ActorManager system, String name, String Dest ) {
			super(system, name);
			this.dest = Dest;
		}
		@Override
		protected void processMessage(Message message) throws Exception {
			logger.info( this.getActorID() + ": Ping");
			Thread.sleep(1000);
			logger.info( this.getActorID() + ": Pong");
			this.getActorManager().tell(this.dest, new Message(this,null) );
		}
	}

    final static Logger 		logger  = LoggerFactory.getLogger(App.class);
    final static ActorManager 	ActrSys = new ActorManager(1);

    public String getGreeting() {
        return "Hello World!";
    }

    public void test_1() throws Exception {
    	var actor_1 = new Actor(ActrSys,"Actor_1","Actor_2");
    	var actor_2 = new Actor(ActrSys,"Actor_2","Actor_1");
    	ActrSys.tell("Actor_1", new Message(null,null) );
    }
    
    public void match1() throws Exception  {
    	String topic	= "SIG";
    	String filter 	= "SIG/#";
    	
		boolean match = twx.core.string.StringTopicMatcher.match(filter, topic);;
		logger.info( "Pattern: " + filter + "  Topic: " +  topic + "  Match: " +  match);
    }
    
    public static void main(String[] args) {
    	var app 	= new App();
        var scanner	= new Scanner(System.in);
        
        logger.info("---------- Start-App ----------");
        
        try {
        	// 	app.runApp();
        	//	app.runThingTasks2();
        	// app.test_1();
        	app.match1();
/*        	
        	while (true){
        		String s = scanner.next();
        		if(s.equals("q")) 
        			break;
        		System.out.println(s);
        	}
*/  
        	ActrSys.shutdown();
        }
        catch(Exception ex) {
        	logger.error(ex.getMessage());
        }
        logger.info( "---------- Exit-App ----------");
    }
}
