/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twx.core;

import java.util.Scanner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

	final static Logger 		logger  = LoggerFactory.getLogger(App.class);
    
    public String getGreeting() {
        return "Hello World!";
    }

    public void test_1() throws Exception {

	}
    
    public void match1() throws Exception  {
    	String topic	= "SIG";
    	String filter 	= "SIG/#";
    	
		boolean match = twx.core.string.StringTopicMatcher.match(filter, topic);;
		logger.info( "Pattern: " + filter + "  Topic: " +  topic + "  Match: " +  match);
    }
    
    public static void main(String[] args) {
    	var app 	= new App();
        var scanner	= new Scanner(System.in);
        
        logger.info("---------- Start-App ----------");
        
        try {
        	// 	app.runApp();B
        	//	app.runThingTasks2();
        	// app.test_1();
        	app.match1();
/*        	
        	while (true){
        		String s = scanner.next();
        		if(s.equals("q")) 
        			break;
        		System.out.println(s);
        	}
*/  
        }
        catch(Exception ex) {
        	logger.error(ex.getMessage());
        }
        logger.info( "---------- Exit-App ----------");
    }
}
